import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../dist/js/game.js';import {build,upgrade,sell,updateTowers,statsFor} from '../dist/js/towers.js';import {spawnEnemy,hit,updateEnemies} from '../dist/js/enemies.js';import {ability} from '../dist/js/hero.js';import {useItem} from '../dist/js/shop.js';import {fresh,load,save,exportSave,importSave,migrate} from '../dist/js/save.js';import {LEVELS,nearestRoad} from '../dist/js/levels.js';import {TOWERS} from '../dist/js/data/towers.js';import {ENEMIES} from '../dist/js/data/enemies.js';import {wavesFor} from '../dist/js/data/waves.js';
const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
function game(){memory.clear();const g=new Game();g.audio={play(){},start(){}};return g;}
function step(g,seconds){for(let i=0;i<seconds*30&&!g.outcome;i++)g.update(1/30);}
test('exact base curves, valid content, three region bosses',()=>{assert.equal(TOWERS.archer.tiers[0].cost,70);assert.deepEqual(TOWERS.magic.tiers[2].damage,[34,56]);assert.equal(LEVELS.length,8);assert.deepEqual(LEVELS.filter(l=>l.boss).map(l=>l.boss),['harvester','hollowking','ashentyrant']);for(const [i,l]of LEVELS.entries()){assert.ok(wavesFor(l,i).length>=7);for(const w of wavesFor(l,i))for(const e of w)assert.ok(ENEMIES[e.type]);for(const e of Object.values(ENEMIES))assert.ok(!(e.armor&&e.resist));}});
test('build, branch, instant squad restoration and 70% sell',()=>{const g=game();g.gold=3000;assert.ok(build(g,'barracks',0));const t=g.towers[0];assert.equal(g.soldiers.length,3);g.soldiers[0].hp=0;assert.ok(upgrade(g,t));assert.equal(g.soldiers[0].hp,100);upgrade(g,t);upgrade(g,t,'sentinels');assert.equal(statsFor(t).armor,.65);const before=g.gold;sell(g,t);assert.equal(g.gold-before,Math.floor((70+110+160+230)*.7));assert.equal(g.soldiers.length,0);assert.equal(g.towers.length,0);});
test('soldiers physically stop a husk, flyers and tunneling enemies pass',()=>{const g=game();build(g,'barracks',0);const s=g.soldiers[0];let e=spawnEnemy(g,'husk',g.towers[0].rally.progress);s.x=e.x;s.y=e.y;const before=e.progress;updateEnemies(g,.1);assert.equal(e.progress,before);assert.ok(s.hp<s.maxHP);g.enemies=[];s.blockedBy=null;e=spawnEnemy(g,'wraith',before);updateEnemies(g,.1);assert.ok(e.progress>before);g.enemies=[];e=spawnEnemy(g,'burrower',before);updateEnemies(g,.1);assert.ok(e.progress>before);});
test('physical armor and magic resistance apply independently',()=>{const g=game(),e=spawnEnemy(g,'revenant');hit(g,e,100);assert.equal(e.hp,380);hit(g,e,100,'magic');assert.equal(e.hp,280);const c=spawnEnemy(g,'chanter');hit(g,c,50,'magic');assert.equal(c.hp,90);hit(g,c,50);assert.equal(c.hp,40);});
test('artillery cannot hit flyers, magic can',()=>{const g=game();g.gold=500;build(g,'artillery',0);const e=spawnEnemy(g,'wraith',100);e.x=g.towers[0].x;e.y=g.towers[0].y;updateTowers(g,4);assert.equal(e.hp,e.maxHP);sell(g,g.towers[0]);build(g,'magic',0);updateTowers(g,2);assert.ok(e.hp<e.maxHP);});
test('abilities, targeted supplies, and cooldowns',()=>{const g=game(),e=spawnEnemy(g,'blightclad');e.x=g.hero.x;e.y=g.hero.y;assert.ok(ability(g,'q'));assert.equal(g.hero.q,22);assert.equal(ability(g,'q'),false);const gems=g.save.gems;assert.ok(useItem(g,'meteor'));assert.equal(g.save.gems,gems);assert.equal(g.targeting,'meteor');assert.ok(useItem(g,'meteor',{x:e.x,y:e.y}));assert.equal(g.save.gems,gems-8);assert.ok(e.hp<=0);});
test('versioned save roundtrip survives new game instances and corrupt data',()=>{const g=game();g.save.stars={0:3,1:2};g.save.unlocked=2;g.save.heroXP=134;g.save.meta.towers=2;g.save.settings.sound=false;g.save.gems=47;g.persist();const reopened=new Game();assert.deepEqual(reopened.save,g.save);const encoded=exportSave(g.save);memory.clear();assert.deepEqual(importSave(encoded),g.save);assert.deepEqual(load(),g.save);assert.equal(migrate({version:1,gems:5}).version,2);assert.throws(()=>importSave('not a valid save'));});
test('early call awards time-scaled gold and cooldown reduction',()=>{const g=game();g.wave=1;g.intermission=15;g.hero.q=20;const before=g.gold;assert.ok(g.action('wave'));assert.equal(g.gold-before,12);assert.ok(g.hero.q<20);assert.equal(g.action('wave'),false);});
test('Iron restricts towers and any gate breach fails',()=>{const g=game();g.save.settings.difficulty='iron';g.reset(0);assert.equal(build(g,'barracks',0),false);assert.equal(g.lives,1);spawnEnemy(g,'husk',g.path.length);updateEnemies(g,.1);assert.equal(g.outcome.victory,false);});
test('opening level is winnable with an affordable three-tower opening',()=>{const g=game();build(g,'archer',0);build(g,'barracks',1);build(g,'archer',2);g.action('wave');let elapsed=0;while(!g.outcome&&elapsed<900){if(g.intermission>0){if(g.gold>=100&&!g.towers.some(t=>t.type==='magic'))build(g,'magic',3);else{const archer=g.towers.find(t=>t.type==='archer'&&t.tier<2);if(archer&&g.gold>=TOWERS.archer.tiers[archer.tier+1].cost)upgrade(g,archer);}g.action('wave');}step(g,1);elapsed++;}assert.ok(g.outcome,'campaign should finish');assert.equal(g.outcome.victory,true);assert.ok(g.lives>=18,`expected generous opening, got ${g.lives} lives`);console.log(`Opening balance: ${g.lives} lives, ${g.kills} kills, ${elapsed}s simulated.`);});
test('all eight Normal missions are beatable with earned progression and branching',()=>{const priorRandom=Math.random;let seed=12345;Math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};try{for(let level=0;level<8;level++){const g=game(),rank=Math.min(3,Math.floor(level/2));g.save.meta={towers:rank,heroes:rank,economy:rank};g.save.heroXP=level*100;g.reset(level);const order=['archer','magic','barracks','archer','artillery','magic','archer','magic'];function spend(){for(let i=0;i<8;i++)if(!g.towers.some(t=>t.plot===i)&&g.gold>=TOWERS[order[i]].tiers[0].cost)build(g,order[i],i);for(const t of g.towers.filter(t=>t.type!=='barracks')){if(t.tier<2&&g.gold>=TOWERS[t.type].tiers[t.tier+1].cost)upgrade(g,t);else if(t.tier===2&&!t.branch){const branch=Object.keys(TOWERS[t.type].branches)[0];if(g.gold>=TOWERS[t.type].branches[branch].cost)upgrade(g,t,branch);}}}spend();g.action('wave');for(let tick=0;tick<36000&&!g.outcome;tick++){if(g.intermission>0){spend();g.action('wave');}if(g.hero.q===0&&g.enemies.some(e=>Math.hypot(e.x-g.hero.x,e.y-g.hero.y)<45))g.action('q');if(g.hero.w===0&&g.enemies.length>6)g.action('w');g.update(.05);}assert.ok(g.outcome?.victory,`Mission ${level+1} should be beatable; wave ${g.wave}, lives ${g.lives}`);console.log(`Mission ${level+1}: ${g.lives} lives, ${g.outcome.stars} stars.`);}}finally{Math.random=priorRandom;}});
test('pausing freezes combat and blocks early calls',()=>{const g=game();g.paused=true;assert.equal(g.action('wave'),false);const time=g.time;g.update(1);assert.equal(g.time,time);});
